name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "38_deployment_test" ]
#  pull_request:
#    branches: [ "38_deployment_test" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: cd /home/runner/work/banking-app/banking-app/bankingapp && mvn clean package -DskipTests
      - run: mkdir staging && mv /home/runner/work/banking-app/banking-app/bankingapp/target/bankingapp-0.0.1-SNAPSHOT.jar /home/runner/work/banking-app/banking-app/bankingapp/target/bankingapp-0.0.1-SNAPSHOT-${{ env.build-number }}.jar && cp  /home/runner/work/banking-app/banking-app/bankingapp/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
