name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "38_deployment_test" ]
  pull_request:
    branches: [ "38_deployment_test" ]

env:
  build-number: ${{github_run_number}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/bankingapp.jar target/bankingapp-${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 3
